# Generated by Django 5.2.13 on 2026-04-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0059_alter_company_country_alter_observer_country_and_more"),
    ]

    operations = [
        # Remove parler translation models from ORM state only (keep DB tables
        # intact so the subsequent data migration can read from them).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="functionalitytranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="functionalitytranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="observertranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="observertranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="operatortypetranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="operatortypetranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="regulationtranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="regulationtranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="regulatortranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="regulatortranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="sectortranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="sectortranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="servicetranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="servicetranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="entitycategorytranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="entitycategorytranslation",
                    name="master",
                ),
                migrations.DeleteModel(name="EntityCategoryTranslation"),
                migrations.DeleteModel(name="FunctionalityTranslation"),
                migrations.DeleteModel(name="ObserverTranslation"),
                migrations.DeleteModel(name="OperatorTypeTranslation"),
                migrations.DeleteModel(name="RegulationTranslation"),
                migrations.DeleteModel(name="RegulatorTranslation"),
                migrations.DeleteModel(name="SectorTranslation"),
                migrations.DeleteModel(name="ServiceTranslation"),
            ],
            database_operations=[],  # Keep DB tables for the data migration
        ),
        # Add new modeltranslation fields to main models
        migrations.AddField(
            model_name="entitycategory",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="entitycategory",
            name="label_de",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="entitycategory",
            name="label_en",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="entitycategory",
            name="label_fr",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="entitycategory",
            name="label_nl",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="functionality",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="functionality",
            name="name_de",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="functionality",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="functionality",
            name="name_fr",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="functionality",
            name="name_nl",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="description_de",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="description_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="description_fr",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="description_nl",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="full_name",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Full name"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="full_name_de",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Full name"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="full_name_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Full name"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="full_name_fr",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Full name"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="full_name_nl",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Full name"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="name_de",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="name_fr",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="name_nl",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="operatortype",
            name="type",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Type"
            ),
        ),
        migrations.AddField(
            model_name="operatortype",
            name="type_de",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Type"
            ),
        ),
        migrations.AddField(
            model_name="operatortype",
            name="type_en",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Type"
            ),
        ),
        migrations.AddField(
            model_name="operatortype",
            name="type_fr",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Type"
            ),
        ),
        migrations.AddField(
            model_name="operatortype",
            name="type_nl",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Type"
            ),
        ),
        migrations.AddField(
            model_name="regulation",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="regulation",
            name="label_de",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="regulation",
            name="label_en",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="regulation",
            name="label_fr",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="regulation",
            name="label_nl",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="description_de",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="description_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="description_fr",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="description_nl",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="full_name",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Full name"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="full_name_de",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Full name"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="full_name_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Full name"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="full_name_fr",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Full name"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="full_name_nl",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Full name"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="name_de",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="name_fr",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="regulator",
            name="name_nl",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_de",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_fr",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="name_nl",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_de",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_fr",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="name_nl",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, verbose_name="Name"
            ),
        ),
    ]
