# Generated by Django 5.2.13 on 2026-04-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0057_alter_incident_incident_timezone_and_more"),
    ]

    operations = [
        # Remove parler translation models from ORM state only (keep DB tables
        # intact so the subsequent data migration can read from them).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="impacttranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="impacttranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="predefinedanswertranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="predefinedanswertranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="questioncategorytranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="questioncategorytranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="questiontranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="questiontranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="sectorregulationtranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="sectorregulationtranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="sectorregulationworkflowemailtranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="sectorregulationworkflowemailtranslation",
                    name="master",
                ),
                migrations.AlterUniqueTogether(
                    name="workflowtranslation",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="workflowtranslation",
                    name="master",
                ),
                migrations.DeleteModel(name="EmailTranslation"),
                migrations.DeleteModel(name="ImpactTranslation"),
                migrations.DeleteModel(name="PredefinedAnswerTranslation"),
                migrations.DeleteModel(name="QuestionCategoryTranslation"),
                migrations.DeleteModel(name="QuestionTranslation"),
                migrations.DeleteModel(name="SectorRegulationTranslation"),
                migrations.DeleteModel(name="SectorRegulationWorkflowEmailTranslation"),
                migrations.DeleteModel(name="WorkflowTranslation"),
            ],
            database_operations=[],  # Keep DB tables for the data migration
        ),
        # Add new modeltranslation fields to main models
        migrations.AddField(
            model_name="email",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Available placeholders: #INCIDENT_NOTIFICATION_DATE#,\n            #INCIDENT_DETECTION_DATE#,\n            #INCIDENT_STARTING_DATE#,\n            #INCIDENT_ID#,\n            #DEADLINE#",
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="content_de",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Available placeholders: #INCIDENT_NOTIFICATION_DATE#,\n            #INCIDENT_DETECTION_DATE#,\n            #INCIDENT_STARTING_DATE#,\n            #INCIDENT_ID#,\n            #DEADLINE#",
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="content_en",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Available placeholders: #INCIDENT_NOTIFICATION_DATE#,\n            #INCIDENT_DETECTION_DATE#,\n            #INCIDENT_STARTING_DATE#,\n            #INCIDENT_ID#,\n            #DEADLINE#",
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="content_fr",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Available placeholders: #INCIDENT_NOTIFICATION_DATE#,\n            #INCIDENT_DETECTION_DATE#,\n            #INCIDENT_STARTING_DATE#,\n            #INCIDENT_ID#,\n            #DEADLINE#",
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="content_nl",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Available placeholders: #INCIDENT_NOTIFICATION_DATE#,\n            #INCIDENT_DETECTION_DATE#,\n            #INCIDENT_STARTING_DATE#,\n            #INCIDENT_ID#,\n            #DEADLINE#",
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="subject",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Subject"
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="subject_de",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Subject",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="subject_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Subject",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="subject_fr",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Subject",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="subject_nl",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Subject",
            ),
        ),
        migrations.AddField(
            model_name="impact",
            name="headline",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="impact",
            name="headline_de",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="impact",
            name="headline_en",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="impact",
            name="headline_fr",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="impact",
            name="headline_nl",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="impact",
            name="label",
            field=models.TextField(blank=True, default="", verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="impact",
            name="label_de",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="impact",
            name="label_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="impact",
            name="label_fr",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="impact",
            name="label_nl",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="predefinedanswer",
            name="predefined_answer",
            field=models.TextField(blank=True, default="", verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="predefinedanswer",
            name="predefined_answer_de",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Answer"
            ),
        ),
        migrations.AddField(
            model_name="predefinedanswer",
            name="predefined_answer_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Answer"
            ),
        ),
        migrations.AddField(
            model_name="predefinedanswer",
            name="predefined_answer_fr",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Answer"
            ),
        ),
        migrations.AddField(
            model_name="predefinedanswer",
            name="predefined_answer_nl",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Answer"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="label",
            field=models.TextField(blank=True, default="", verbose_name="Label"),
        ),
        migrations.AddField(
            model_name="question",
            name="label_de",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="label_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="label_fr",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="label_nl",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="tooltip",
            field=models.TextField(blank=True, null=True, verbose_name="Tooltip"),
        ),
        migrations.AddField(
            model_name="question",
            name="tooltip_de",
            field=models.TextField(blank=True, null=True, verbose_name="Tooltip"),
        ),
        migrations.AddField(
            model_name="question",
            name="tooltip_en",
            field=models.TextField(blank=True, null=True, verbose_name="Tooltip"),
        ),
        migrations.AddField(
            model_name="question",
            name="tooltip_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Tooltip"),
        ),
        migrations.AddField(
            model_name="question",
            name="tooltip_nl",
            field=models.TextField(blank=True, null=True, verbose_name="Tooltip"),
        ),
        migrations.AddField(
            model_name="questioncategory",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="questioncategory",
            name="label_de",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="questioncategory",
            name="label_en",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="questioncategory",
            name="label_fr",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="questioncategory",
            name="label_nl",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="sectorregulation",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="sectorregulation",
            name="name_de",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="sectorregulation",
            name="name_en",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="sectorregulation",
            name="name_fr",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="sectorregulation",
            name="name_nl",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="sectorregulationworkflowemail",
            name="headline",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Email subject"
            ),
        ),
        migrations.AddField(
            model_name="sectorregulationworkflowemail",
            name="headline_de",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Email subject",
            ),
        ),
        migrations.AddField(
            model_name="sectorregulationworkflowemail",
            name="headline_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Email subject",
            ),
        ),
        migrations.AddField(
            model_name="sectorregulationworkflowemail",
            name="headline_fr",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Email subject",
            ),
        ),
        migrations.AddField(
            model_name="sectorregulationworkflowemail",
            name="headline_nl",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Email subject",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="description_de",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="description_en",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="description_fr",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="description_nl",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="label_de",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="label_en",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="label_fr",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="label_nl",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, verbose_name="Label"
            ),
        ),
    ]
